let currentQuestion=0;
var score=0;
const questions = [

       {
           "questionNo": 1,
           "isPara":0,
           "para":null,
           "question":"National Income estimates in India are prepared by",
           "option1":"State bank of india",
           "option2":"Reserve Bank of India",
           "option3":"Central statistical organisation",
           "option4":" Indian statistical Institute",
           "answer": "option3",
           "visited": 0,
           "reviewed":0,
           "answered":0,
       },
       {
           "questionNo": 2,
           "isPara":0,
           "para":null,           
           "question":"MS-Word is an example of ",
           "option1":"An operating system",
           "option2":"A processing device",
           "option3":"Application software",
           "option4":"An input device",
           "answer": "option3",
           "visited": 0,
           "reviewed":0,
           "answered":0,
       },
       {
           "questionNo": 3,
           "isPara":0,
           "para":null,
            "question":"Ctrl, Shift and Alt are called .......... keys.",
           "option1":"modifier",
           "option2":"function",
           "option3":"alphanumeric",
           "option4":"adjustment",
           "answer": "option1",
           "visited": 0,
           "reviewed":0,
           "answered":0,       },
       {
           "questionNo": 4,
           "isPara":1,
           "para":"Suresh is having a garden near delhi. In the garden, there are different types of trees and flower plants.One dar due to heavy rain and storn one of the tress got broken. the hieght of broken part fell down is 20m and unbroken part is 15m. Using pythagoras theorem answer the foll. question",
            "question":"Find the Length of the broken part",
           "option1":"15m",
           "option2":"20m",
           "option3":"25m",
           "option4":"5m",
           "answer": "option1",
           "visited": 0,
           "reviewed":0,
           "answered":0,
        },

       {
           "questionNo": 5,
           "isPara":0,
           "para":null,
            "question":"A computer cannot 'boot' if it does not have the _____",
           "option1":"Compiler",
           "option2":"function",
           "option3":"Operating system",
           "option4":"adjustment",
           "answer": "option3",
           
           "visited": 0,
           "reviewed":0,
           "answered":0,
       },
       {
           "questionNo": 6,
           "isPara":1,
           "para":"It showed an electrical current in which 3 resistors having resistor R1,R2 and R3 resp are join end to end i.e in series. While the combination of the resistor in which 3 resistors connected together which points X and Y as said to be parallel",
            "question":"The total potential difference across a combination of a resistor in series is equal to",
           "option1":"V1 + V2 + V3",
           "option2":"V1",
           "option3":"V1 - V2",
           "option4":"none",
           "answer": "option3",
           "visited": 0,
           "reviewed":0,
           "answered":0,
       }

    
]